// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma-next contract emit'.
// To regenerate, run: prisma-next contract emit
import type { CodecTypes as PgTypes } from '@prisma-next/adapter-postgres/codec-types';
import type { JsonValue } from '@prisma-next/adapter-postgres/codec-types';
import type { Char } from '@prisma-next/adapter-postgres/codec-types';
import type { Varchar } from '@prisma-next/adapter-postgres/codec-types';
import type { Numeric } from '@prisma-next/adapter-postgres/codec-types';
import type { Bit } from '@prisma-next/adapter-postgres/codec-types';
import type { VarBit } from '@prisma-next/adapter-postgres/codec-types';
import type { Timestamp } from '@prisma-next/adapter-postgres/codec-types';
import type { Timestamptz } from '@prisma-next/adapter-postgres/codec-types';
import type { Time } from '@prisma-next/adapter-postgres/codec-types';
import type { Timetz } from '@prisma-next/adapter-postgres/codec-types';
import type { Interval } from '@prisma-next/adapter-postgres/codec-types';

import type {
  ExecutionHashBase,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma-next/contract/types';
import type {
  SqlContract,
  SqlStorage,
  SqlMappings,
  ModelDefinition,
} from '@prisma-next/sql-contract/types';

export type StorageHash =
  StorageHashBase<'sha256:6ccb7a1fedea2a56d2ca9c90f3420fa73affca3a27b1c0b5acc8e809840280dc'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'sha256:f8f8f7f23ce43cd1b7344e9c97651617112e7d216338d43f071a445b1fca8627'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type OperationTypes = Record<string, never>;
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? CodecTypes[CodecId] extends { readonly output: infer O }
    ? O extends Date | bigint
      ? O
      : Encoded
    : Encoded
  : Encoded;

export type Contract = SqlContract<
  {
    readonly tables: {
      readonly user: {
        columns: {
          readonly id: {
            readonly nativeType: 'text';
            readonly codecId: 'pg/text@1';
            readonly nullable: false;
          };
          readonly name: {
            readonly nativeType: 'text';
            readonly codecId: 'pg/text@1';
            readonly nullable: false;
          };
          readonly email: {
            readonly nativeType: 'text';
            readonly codecId: 'pg/text@1';
            readonly nullable: false;
          };
          readonly emailVerified: {
            readonly nativeType: 'bool';
            readonly codecId: 'pg/bool@1';
            readonly nullable: false;
            readonly default: {
              readonly kind: 'literal';
              readonly value: DefaultLiteralValue<'pg/bool@1', false>;
            };
          };
          readonly image: {
            readonly nativeType: 'text';
            readonly codecId: 'pg/text@1';
            readonly nullable: true;
          };
          readonly createdAt: {
            readonly nativeType: 'timestamptz';
            readonly codecId: 'pg/timestamptz@1';
            readonly nullable: false;
            readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
          };
          readonly updatedAt: {
            readonly nativeType: 'timestamptz';
            readonly codecId: 'pg/timestamptz@1';
            readonly nullable: false;
            readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
          };
        };
        primaryKey: { readonly columns: readonly ['id'] };
        uniques: readonly [{ readonly columns: readonly ['email'] }];
        indexes: readonly [];
        foreignKeys: readonly [];
      };
      readonly session: {
        columns: {
          readonly id: {
            readonly nativeType: 'text';
            readonly codecId: 'pg/text@1';
            readonly nullable: false;
          };
          readonly expiresAt: {
            readonly nativeType: 'timestamptz';
            readonly codecId: 'pg/timestamptz@1';
            readonly nullable: false;
          };
          readonly token: {
            readonly nativeType: 'text';
            readonly codecId: 'pg/text@1';
            readonly nullable: false;
          };
          readonly createdAt: {
            readonly nativeType: 'timestamptz';
            readonly codecId: 'pg/timestamptz@1';
            readonly nullable: false;
            readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
          };
          readonly updatedAt: {
            readonly nativeType: 'timestamptz';
            readonly codecId: 'pg/timestamptz@1';
            readonly nullable: false;
            readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
          };
          readonly ipAddress: {
            readonly nativeType: 'text';
            readonly codecId: 'pg/text@1';
            readonly nullable: true;
          };
          readonly userAgent: {
            readonly nativeType: 'text';
            readonly codecId: 'pg/text@1';
            readonly nullable: true;
          };
          readonly userId: {
            readonly nativeType: 'text';
            readonly codecId: 'pg/text@1';
            readonly nullable: false;
          };
        };
        primaryKey: { readonly columns: readonly ['id'] };
        uniques: readonly [{ readonly columns: readonly ['token'] }];
        indexes: readonly [{ readonly columns: readonly ['userId'] }];
        foreignKeys: readonly [
          {
            readonly columns: readonly ['userId'];
            readonly references: { readonly table: 'user'; readonly columns: readonly ['id'] };
            readonly constraint: true;
            readonly index: true;
          },
        ];
      };
      readonly account: {
        columns: {
          readonly id: {
            readonly nativeType: 'text';
            readonly codecId: 'pg/text@1';
            readonly nullable: false;
          };
          readonly accountId: {
            readonly nativeType: 'text';
            readonly codecId: 'pg/text@1';
            readonly nullable: false;
          };
          readonly providerId: {
            readonly nativeType: 'text';
            readonly codecId: 'pg/text@1';
            readonly nullable: false;
          };
          readonly userId: {
            readonly nativeType: 'text';
            readonly codecId: 'pg/text@1';
            readonly nullable: false;
          };
          readonly accessToken: {
            readonly nativeType: 'text';
            readonly codecId: 'pg/text@1';
            readonly nullable: true;
          };
          readonly refreshToken: {
            readonly nativeType: 'text';
            readonly codecId: 'pg/text@1';
            readonly nullable: true;
          };
          readonly idToken: {
            readonly nativeType: 'text';
            readonly codecId: 'pg/text@1';
            readonly nullable: true;
          };
          readonly accessTokenExpiresAt: {
            readonly nativeType: 'timestamptz';
            readonly codecId: 'pg/timestamptz@1';
            readonly nullable: true;
          };
          readonly refreshTokenExpiresAt: {
            readonly nativeType: 'timestamptz';
            readonly codecId: 'pg/timestamptz@1';
            readonly nullable: true;
          };
          readonly scope: {
            readonly nativeType: 'text';
            readonly codecId: 'pg/text@1';
            readonly nullable: true;
          };
          readonly password: {
            readonly nativeType: 'text';
            readonly codecId: 'pg/text@1';
            readonly nullable: true;
          };
          readonly createdAt: {
            readonly nativeType: 'timestamptz';
            readonly codecId: 'pg/timestamptz@1';
            readonly nullable: false;
            readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
          };
          readonly updatedAt: {
            readonly nativeType: 'timestamptz';
            readonly codecId: 'pg/timestamptz@1';
            readonly nullable: false;
            readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
          };
        };
        primaryKey: { readonly columns: readonly ['id'] };
        uniques: readonly [];
        indexes: readonly [{ readonly columns: readonly ['userId'] }];
        foreignKeys: readonly [
          {
            readonly columns: readonly ['userId'];
            readonly references: { readonly table: 'user'; readonly columns: readonly ['id'] };
            readonly constraint: true;
            readonly index: true;
          },
        ];
      };
      readonly verification: {
        columns: {
          readonly id: {
            readonly nativeType: 'text';
            readonly codecId: 'pg/text@1';
            readonly nullable: false;
          };
          readonly identifier: {
            readonly nativeType: 'text';
            readonly codecId: 'pg/text@1';
            readonly nullable: false;
          };
          readonly value: {
            readonly nativeType: 'text';
            readonly codecId: 'pg/text@1';
            readonly nullable: false;
          };
          readonly expiresAt: {
            readonly nativeType: 'timestamptz';
            readonly codecId: 'pg/timestamptz@1';
            readonly nullable: false;
          };
          readonly createdAt: {
            readonly nativeType: 'timestamptz';
            readonly codecId: 'pg/timestamptz@1';
            readonly nullable: false;
            readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
          };
          readonly updatedAt: {
            readonly nativeType: 'timestamptz';
            readonly codecId: 'pg/timestamptz@1';
            readonly nullable: false;
            readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
          };
        };
        primaryKey: { readonly columns: readonly ['id'] };
        uniques: readonly [];
        indexes: readonly [{ readonly columns: readonly ['identifier'] }];
        foreignKeys: readonly [];
      };
      readonly todo: {
        columns: {
          readonly id: {
            readonly nativeType: 'int4';
            readonly codecId: 'pg/int4@1';
            readonly nullable: false;
            readonly default: { readonly kind: 'function'; readonly expression: 'autoincrement()' };
          };
          readonly text: {
            readonly nativeType: 'text';
            readonly codecId: 'pg/text@1';
            readonly nullable: false;
          };
          readonly completed: {
            readonly nativeType: 'bool';
            readonly codecId: 'pg/bool@1';
            readonly nullable: false;
            readonly default: {
              readonly kind: 'literal';
              readonly value: DefaultLiteralValue<'pg/bool@1', false>;
            };
          };
        };
        primaryKey: { readonly columns: readonly ['id'] };
        uniques: readonly [];
        indexes: readonly [];
        foreignKeys: readonly [];
      };
    };
    readonly types: Record<string, never>;
  },
  {
    readonly User: {
      storage: { readonly table: 'user' };
      fields: {
        readonly id: CodecTypes['pg/text@1']['output'];
        readonly name: CodecTypes['pg/text@1']['output'];
        readonly email: CodecTypes['pg/text@1']['output'];
        readonly emailVerified: CodecTypes['pg/bool@1']['output'];
        readonly image: CodecTypes['pg/text@1']['output'] | null;
        readonly createdAt: CodecTypes['pg/timestamptz@1']['output'];
        readonly updatedAt: CodecTypes['pg/timestamptz@1']['output'];
      };
    };
    readonly Session: {
      storage: { readonly table: 'session' };
      fields: {
        readonly id: CodecTypes['pg/text@1']['output'];
        readonly expiresAt: CodecTypes['pg/timestamptz@1']['output'];
        readonly token: CodecTypes['pg/text@1']['output'];
        readonly createdAt: CodecTypes['pg/timestamptz@1']['output'];
        readonly updatedAt: CodecTypes['pg/timestamptz@1']['output'];
        readonly ipAddress: CodecTypes['pg/text@1']['output'] | null;
        readonly userAgent: CodecTypes['pg/text@1']['output'] | null;
        readonly userId: CodecTypes['pg/text@1']['output'];
      };
    };
    readonly Account: {
      storage: { readonly table: 'account' };
      fields: {
        readonly id: CodecTypes['pg/text@1']['output'];
        readonly accountId: CodecTypes['pg/text@1']['output'];
        readonly providerId: CodecTypes['pg/text@1']['output'];
        readonly userId: CodecTypes['pg/text@1']['output'];
        readonly accessToken: CodecTypes['pg/text@1']['output'] | null;
        readonly refreshToken: CodecTypes['pg/text@1']['output'] | null;
        readonly idToken: CodecTypes['pg/text@1']['output'] | null;
        readonly accessTokenExpiresAt: CodecTypes['pg/timestamptz@1']['output'] | null;
        readonly refreshTokenExpiresAt: CodecTypes['pg/timestamptz@1']['output'] | null;
        readonly scope: CodecTypes['pg/text@1']['output'] | null;
        readonly password: CodecTypes['pg/text@1']['output'] | null;
        readonly createdAt: CodecTypes['pg/timestamptz@1']['output'];
        readonly updatedAt: CodecTypes['pg/timestamptz@1']['output'];
      };
    };
    readonly Verification: {
      storage: { readonly table: 'verification' };
      fields: {
        readonly id: CodecTypes['pg/text@1']['output'];
        readonly identifier: CodecTypes['pg/text@1']['output'];
        readonly value: CodecTypes['pg/text@1']['output'];
        readonly expiresAt: CodecTypes['pg/timestamptz@1']['output'];
        readonly createdAt: CodecTypes['pg/timestamptz@1']['output'];
        readonly updatedAt: CodecTypes['pg/timestamptz@1']['output'];
      };
    };
    readonly Todo: {
      storage: { readonly table: 'todo' };
      fields: {
        readonly id: CodecTypes['pg/int4@1']['output'];
        readonly text: CodecTypes['pg/text@1']['output'];
        readonly completed: CodecTypes['pg/bool@1']['output'];
      };
    };
  },
  {
    readonly user: {
      readonly sessions: {
        readonly to: 'Session';
        readonly cardinality: '1:N';
        readonly on: {
          readonly parentCols: readonly ['id'];
          readonly childCols: readonly ['userId'];
        };
      };
      readonly accounts: {
        readonly to: 'Account';
        readonly cardinality: '1:N';
        readonly on: {
          readonly parentCols: readonly ['id'];
          readonly childCols: readonly ['userId'];
        };
      };
    };
    readonly session: {
      readonly user: {
        readonly to: 'User';
        readonly cardinality: 'N:1';
        readonly on: {
          readonly parentCols: readonly ['userId'];
          readonly childCols: readonly ['id'];
        };
      };
    };
    readonly account: {
      readonly user: {
        readonly to: 'User';
        readonly cardinality: 'N:1';
        readonly on: {
          readonly parentCols: readonly ['userId'];
          readonly childCols: readonly ['id'];
        };
      };
    };
  },
  {
    modelToTable: {
      readonly User: 'user';
      readonly Session: 'session';
      readonly Account: 'account';
      readonly Verification: 'verification';
      readonly Todo: 'todo';
    };
    tableToModel: {
      readonly user: 'User';
      readonly session: 'Session';
      readonly account: 'Account';
      readonly verification: 'Verification';
      readonly todo: 'Todo';
    };
    fieldToColumn: {
      readonly User: {
        readonly id: 'id';
        readonly name: 'name';
        readonly email: 'email';
        readonly emailVerified: 'emailVerified';
        readonly image: 'image';
        readonly createdAt: 'createdAt';
        readonly updatedAt: 'updatedAt';
      };
      readonly Session: {
        readonly id: 'id';
        readonly expiresAt: 'expiresAt';
        readonly token: 'token';
        readonly createdAt: 'createdAt';
        readonly updatedAt: 'updatedAt';
        readonly ipAddress: 'ipAddress';
        readonly userAgent: 'userAgent';
        readonly userId: 'userId';
      };
      readonly Account: {
        readonly id: 'id';
        readonly accountId: 'accountId';
        readonly providerId: 'providerId';
        readonly userId: 'userId';
        readonly accessToken: 'accessToken';
        readonly refreshToken: 'refreshToken';
        readonly idToken: 'idToken';
        readonly accessTokenExpiresAt: 'accessTokenExpiresAt';
        readonly refreshTokenExpiresAt: 'refreshTokenExpiresAt';
        readonly scope: 'scope';
        readonly password: 'password';
        readonly createdAt: 'createdAt';
        readonly updatedAt: 'updatedAt';
      };
      readonly Verification: {
        readonly id: 'id';
        readonly identifier: 'identifier';
        readonly value: 'value';
        readonly expiresAt: 'expiresAt';
        readonly createdAt: 'createdAt';
        readonly updatedAt: 'updatedAt';
      };
      readonly Todo: { readonly id: 'id'; readonly text: 'text'; readonly completed: 'completed' };
    };
    columnToField: {
      readonly user: {
        readonly id: 'id';
        readonly name: 'name';
        readonly email: 'email';
        readonly emailVerified: 'emailVerified';
        readonly image: 'image';
        readonly createdAt: 'createdAt';
        readonly updatedAt: 'updatedAt';
      };
      readonly session: {
        readonly id: 'id';
        readonly expiresAt: 'expiresAt';
        readonly token: 'token';
        readonly createdAt: 'createdAt';
        readonly updatedAt: 'updatedAt';
        readonly ipAddress: 'ipAddress';
        readonly userAgent: 'userAgent';
        readonly userId: 'userId';
      };
      readonly account: {
        readonly id: 'id';
        readonly accountId: 'accountId';
        readonly providerId: 'providerId';
        readonly userId: 'userId';
        readonly accessToken: 'accessToken';
        readonly refreshToken: 'refreshToken';
        readonly idToken: 'idToken';
        readonly accessTokenExpiresAt: 'accessTokenExpiresAt';
        readonly refreshTokenExpiresAt: 'refreshTokenExpiresAt';
        readonly scope: 'scope';
        readonly password: 'password';
        readonly createdAt: 'createdAt';
        readonly updatedAt: 'updatedAt';
      };
      readonly verification: {
        readonly id: 'id';
        readonly identifier: 'identifier';
        readonly value: 'value';
        readonly expiresAt: 'expiresAt';
        readonly createdAt: 'createdAt';
        readonly updatedAt: 'updatedAt';
      };
      readonly todo: { readonly id: 'id'; readonly text: 'text'; readonly completed: 'completed' };
    };
    codecTypes: PgTypes;
    operationTypes: Record<string, never>;
  },
  StorageHash,
  ExecutionHash,
  ProfileHash
>;

export type Tables = Contract['storage']['tables'];
export type Models = Contract['models'];
export type Relations = Contract['relations'];
