// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma-next contract emit'.
// To regenerate, run: prisma-next contract emit
import type { CodecTypes as PgTypes } from '@prisma-next/adapter-postgres/codec-types';
import type { JsonValue } from '@prisma-next/adapter-postgres/codec-types';
import type { Char } from '@prisma-next/adapter-postgres/codec-types';
import type { Varchar } from '@prisma-next/adapter-postgres/codec-types';
import type { Numeric } from '@prisma-next/adapter-postgres/codec-types';
import type { Bit } from '@prisma-next/adapter-postgres/codec-types';
import type { VarBit } from '@prisma-next/adapter-postgres/codec-types';
import type { Timestamp } from '@prisma-next/adapter-postgres/codec-types';
import type { Timestamptz } from '@prisma-next/adapter-postgres/codec-types';
import type { Time } from '@prisma-next/adapter-postgres/codec-types';
import type { Timetz } from '@prisma-next/adapter-postgres/codec-types';
import type { Interval } from '@prisma-next/adapter-postgres/codec-types';

import type {
  ExecutionHashBase,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma-next/contract/types';
import type {
  SqlContract,
  SqlStorage,
  SqlMappings,
  ModelDefinition,
} from '@prisma-next/sql-contract/types';

export type StorageHash =
  StorageHashBase<'sha256:c2865461090f7e375b02551c34fe8086ec76be23e7d2d5373be4d709bc35735a'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'sha256:670cfaa084208fec640cd80a1864182c43e9a000f4ae282b732c88e26f919e89'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type OperationTypes = Record<string, never>;
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? CodecTypes[CodecId] extends { readonly output: infer O }
    ? O extends Date | bigint
      ? O
      : Encoded
    : Encoded
  : Encoded;

export type Contract = SqlContract<
  {
    readonly tables: {
      readonly pokemon: {
        columns: {
          readonly id: {
            readonly nativeType: 'int4';
            readonly codecId: 'pg/int4@1';
            readonly nullable: false;
            readonly default: { readonly kind: 'function'; readonly expression: 'autoincrement()' };
          };
          readonly dexNumber: {
            readonly nativeType: 'int4';
            readonly codecId: 'pg/int4@1';
            readonly nullable: false;
          };
          readonly name: {
            readonly nativeType: 'text';
            readonly codecId: 'pg/text@1';
            readonly nullable: false;
          };
          readonly primaryType: {
            readonly nativeType: 'text';
            readonly codecId: 'pg/text@1';
            readonly nullable: false;
          };
          readonly secondaryType: {
            readonly nativeType: 'text';
            readonly codecId: 'pg/text@1';
            readonly nullable: true;
          };
          readonly hp: {
            readonly nativeType: 'int4';
            readonly codecId: 'pg/int4@1';
            readonly nullable: false;
          };
          readonly attack: {
            readonly nativeType: 'int4';
            readonly codecId: 'pg/int4@1';
            readonly nullable: false;
          };
          readonly defense: {
            readonly nativeType: 'int4';
            readonly codecId: 'pg/int4@1';
            readonly nullable: false;
          };
          readonly speed: {
            readonly nativeType: 'int4';
            readonly codecId: 'pg/int4@1';
            readonly nullable: false;
          };
          readonly spriteUrl: {
            readonly nativeType: 'text';
            readonly codecId: 'pg/text@1';
            readonly nullable: false;
          };
          readonly isLegendary: {
            readonly nativeType: 'bool';
            readonly codecId: 'pg/bool@1';
            readonly nullable: false;
          };
          readonly createdAt: {
            readonly nativeType: 'timestamptz';
            readonly codecId: 'pg/timestamptz@1';
            readonly nullable: false;
            readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
          };
          readonly updatedAt: {
            readonly nativeType: 'timestamptz';
            readonly codecId: 'pg/timestamptz@1';
            readonly nullable: false;
            readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
          };
        };
        primaryKey: { readonly columns: readonly ['id'] };
        uniques: readonly [
          { readonly columns: readonly ['dexNumber'] },
          { readonly columns: readonly ['name'] },
        ];
        indexes: readonly [
          { readonly columns: readonly ['primaryType'] },
          { readonly columns: readonly ['isLegendary'] },
        ];
        foreignKeys: readonly [];
      };
      readonly spawnPoint: {
        columns: {
          readonly id: {
            readonly nativeType: 'int4';
            readonly codecId: 'pg/int4@1';
            readonly nullable: false;
            readonly default: { readonly kind: 'function'; readonly expression: 'autoincrement()' };
          };
          readonly pokemonId: {
            readonly nativeType: 'int4';
            readonly codecId: 'pg/int4@1';
            readonly nullable: false;
          };
          readonly label: {
            readonly nativeType: 'text';
            readonly codecId: 'pg/text@1';
            readonly nullable: false;
          };
          readonly region: {
            readonly nativeType: 'text';
            readonly codecId: 'pg/text@1';
            readonly nullable: false;
          };
          readonly latitude: {
            readonly nativeType: 'float8';
            readonly codecId: 'pg/float8@1';
            readonly nullable: false;
          };
          readonly longitude: {
            readonly nativeType: 'float8';
            readonly codecId: 'pg/float8@1';
            readonly nullable: false;
          };
          readonly encounterRate: {
            readonly nativeType: 'int4';
            readonly codecId: 'pg/int4@1';
            readonly nullable: false;
          };
          readonly createdAt: {
            readonly nativeType: 'timestamptz';
            readonly codecId: 'pg/timestamptz@1';
            readonly nullable: false;
            readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
          };
        };
        primaryKey: { readonly columns: readonly ['id'] };
        uniques: readonly [];
        indexes: readonly [
          { readonly columns: readonly ['pokemonId'] },
          { readonly columns: readonly ['region'] },
          { readonly columns: readonly ['latitude', 'longitude'] },
        ];
        foreignKeys: readonly [
          {
            readonly columns: readonly ['pokemonId'];
            readonly references: { readonly table: 'pokemon'; readonly columns: readonly ['id'] };
            readonly constraint: true;
            readonly index: true;
          },
        ];
      };
    };
    readonly types: Record<string, never>;
  },
  {
    readonly Pokemon: {
      storage: { readonly table: 'pokemon' };
      fields: {
        readonly id: CodecTypes['pg/int4@1']['output'];
        readonly dexNumber: CodecTypes['pg/int4@1']['output'];
        readonly name: CodecTypes['pg/text@1']['output'];
        readonly primaryType: CodecTypes['pg/text@1']['output'];
        readonly secondaryType: CodecTypes['pg/text@1']['output'] | null;
        readonly hp: CodecTypes['pg/int4@1']['output'];
        readonly attack: CodecTypes['pg/int4@1']['output'];
        readonly defense: CodecTypes['pg/int4@1']['output'];
        readonly speed: CodecTypes['pg/int4@1']['output'];
        readonly spriteUrl: CodecTypes['pg/text@1']['output'];
        readonly isLegendary: CodecTypes['pg/bool@1']['output'];
        readonly createdAt: CodecTypes['pg/timestamptz@1']['output'];
        readonly updatedAt: CodecTypes['pg/timestamptz@1']['output'];
      };
    };
    readonly SpawnPoint: {
      storage: { readonly table: 'spawnPoint' };
      fields: {
        readonly id: CodecTypes['pg/int4@1']['output'];
        readonly pokemonId: CodecTypes['pg/int4@1']['output'];
        readonly label: CodecTypes['pg/text@1']['output'];
        readonly region: CodecTypes['pg/text@1']['output'];
        readonly latitude: CodecTypes['pg/float8@1']['output'];
        readonly longitude: CodecTypes['pg/float8@1']['output'];
        readonly encounterRate: CodecTypes['pg/int4@1']['output'];
        readonly createdAt: CodecTypes['pg/timestamptz@1']['output'];
      };
    };
  },
  Record<string, never>,
  {
    modelToTable: { readonly Pokemon: 'pokemon'; readonly SpawnPoint: 'spawnPoint' };
    tableToModel: { readonly pokemon: 'Pokemon'; readonly spawnPoint: 'SpawnPoint' };
    fieldToColumn: {
      readonly Pokemon: {
        readonly id: 'id';
        readonly dexNumber: 'dexNumber';
        readonly name: 'name';
        readonly primaryType: 'primaryType';
        readonly secondaryType: 'secondaryType';
        readonly hp: 'hp';
        readonly attack: 'attack';
        readonly defense: 'defense';
        readonly speed: 'speed';
        readonly spriteUrl: 'spriteUrl';
        readonly isLegendary: 'isLegendary';
        readonly createdAt: 'createdAt';
        readonly updatedAt: 'updatedAt';
      };
      readonly SpawnPoint: {
        readonly id: 'id';
        readonly pokemonId: 'pokemonId';
        readonly label: 'label';
        readonly region: 'region';
        readonly latitude: 'latitude';
        readonly longitude: 'longitude';
        readonly encounterRate: 'encounterRate';
        readonly createdAt: 'createdAt';
      };
    };
    columnToField: {
      readonly pokemon: {
        readonly id: 'id';
        readonly dexNumber: 'dexNumber';
        readonly name: 'name';
        readonly primaryType: 'primaryType';
        readonly secondaryType: 'secondaryType';
        readonly hp: 'hp';
        readonly attack: 'attack';
        readonly defense: 'defense';
        readonly speed: 'speed';
        readonly spriteUrl: 'spriteUrl';
        readonly isLegendary: 'isLegendary';
        readonly createdAt: 'createdAt';
        readonly updatedAt: 'updatedAt';
      };
      readonly spawnPoint: {
        readonly id: 'id';
        readonly pokemonId: 'pokemonId';
        readonly label: 'label';
        readonly region: 'region';
        readonly latitude: 'latitude';
        readonly longitude: 'longitude';
        readonly encounterRate: 'encounterRate';
        readonly createdAt: 'createdAt';
      };
    };
    codecTypes: PgTypes;
    operationTypes: Record<string, never>;
  },
  StorageHash,
  ExecutionHash,
  ProfileHash
>;

export type Tables = Contract['storage']['tables'];
export type Models = Contract['models'];
export type Relations = Contract['relations'];
