/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamBuilderRouteImport } from './routes/team-builder'
import { Route as IndexRouteImport } from './routes/index'

const TeamBuilderRoute = TeamBuilderRouteImport.update({
  id: '/team-builder',
  path: '/team-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/team-builder': typeof TeamBuilderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/team-builder': typeof TeamBuilderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/team-builder': typeof TeamBuilderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/team-builder'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/team-builder'
  id: '__root__' | '/' | '/team-builder'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TeamBuilderRoute: typeof TeamBuilderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team-builder': {
      id: '/team-builder'
      path: '/team-builder'
      fullPath: '/team-builder'
      preLoaderRoute: typeof TeamBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TeamBuilderRoute: TeamBuilderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
